apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: flux-system
spec:
  interval: 1m
  url: https://releases.rancher.com/server-charts/stable
