apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
      interval: 1m
  
  install:
    remediation:
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  values:
    hostname: rancher.35.231.139.225.nip.io
    rancherImageTag: v2.8.0
    replicas: 1
    
    # Disable TLS/Ingress - we'll use LoadBalancer
    tls: external
    ingress:
      enabled: false
    
    # Disable cert-manager dependency
    global:
      cattle:
        psp:
          enabled: false
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
