# LoadBalancer service for Jaeger UI
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: observability
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 16686
      name: http
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
