apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: jaeger
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    
    allInOne:
      enabled: true
      extraEnv:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    storage:
      type: memory
    
    agent:
      enabled: false
    
    collector:
      enabled: false
    
    query:
      enabled: false
    
    # UI service
    query:
      enabled: false
