apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: deployment
    
    image:
      repository: otel/opentelemetry-collector-contrib
    
    replicaCount: 1
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_http:
              endpoint: 0.0.0.0:14268
            thrift_compact:
              endpoint: 0.0.0.0:6831
        zipkin:
          endpoint: 0.0.0.0:9411
      
      processors:
        batch:
          timeout: 1s
          send_batch_size: 1024
        memory_limiter:
          check_interval: 1s
          limit_mib: 400
          spike_limit_mib: 100
      
      exporters:
        otlp/jaeger:
          endpoint: jaeger-collector.observability.svc:4317
          tls:
            insecure: true
        debug:
          verbosity: detailed
      
      service:
        pipelines:
          traces:
            receivers: [otlp, jaeger, zipkin]
            processors: [memory_limiter, batch]
            exporters: [otlp/jaeger]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [debug]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [debug]
    
    ports:
      otlp:
        enabled: true
        containerPort: 4317
        servicePort: 4317
        protocol: TCP
      otlp-http:
        enabled: true
        containerPort: 4318
        servicePort: 4318
        protocol: TCP
      jaeger-grpc:
        enabled: true
        containerPort: 14250
        servicePort: 14250
        protocol: TCP
      jaeger-thrift:
        enabled: true
        containerPort: 14268
        servicePort: 14268
        protocol: TCP
      jaeger-compact:
        enabled: true
        containerPort: 6831
        servicePort: 6831
        protocol: UDP
      zipkin:
        enabled: true
        containerPort: 9411
        servicePort: 9411
        protocol: TCP
