apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-boutique
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/GoogleCloudPlatform/microservices-demo
  ref:
    branch: main
