# Gatekeeper Policy Manager - Web UI for OPA Gatekeeper
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-policy-manager
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["constraints.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["templates.gatekeeper.sh"]
    resources: ["constrainttemplates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.gatekeeper.sh"]
    resources: ["configs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["status.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["mutations.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["expansion.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-policy-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatekeeper-policy-manager
subjects:
  - kind: ServiceAccount
    name: gatekeeper-policy-manager
    namespace: gatekeeper-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-policy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper-policy-manager
  template:
    metadata:
      labels:
        app: gatekeeper-policy-manager
    spec:
      serviceAccountName: gatekeeper-policy-manager
      containers:
        - name: policy-manager
          image: quay.io/sighup/gatekeeper-policy-manager:v1.0.13
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GK_NAMESPACE
              value: "gatekeeper-system"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-policy-manager
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: gatekeeper-policy-manager
